var config = {

    user1 : {
        public_key : "GBQ2MQODFAREFSDWQZTYEQ6R6VZ7J3MXAOHOKZ3CLQQV5RMTZ22I4GHT",
        secret_key : "SAOKPDDGQHKAYIFYHFMX3HPFB2EM2VX66CDWIW5QI3V266LZ724QYWU3"
    },

    user2 : {
        public_key : "GCRPPJCNU6YCQNFWV5WD6Z6JIJFJEJEAZEAEQRPSTTC22JWULYGFJLWX",
        secret_key : "SDJ6LDNYVALXNVXPLUNJMRDSV3QRXAZCDPSNTFZQBTVVA2FXWD2OF64O"
    },

    issuer : {
        public_key : "GDGPWKNUC5S5VN6H3TBESLKHNOWZ5YHJBIGXOVS5U6RJMSLI6VW2G55H",
        secret_key : "SD2YF722FPD2N2V34E5N2FWQRDVQAPJKBRHKYLCGTASLALST2ZQSZRSK"
    },

    server : "https://horizon-testnet.stellar.org",
    network : "test",

}

module.exports = config